### PR TITLE
Añadido párrafo inicial a la página principal

### PR DESCRIPTION
**Pull request by Juanlu001**
@Qkolnek @kikocorreoso @yamila-moreno

### CODE REVIEW

**Comment by Juanlu001** [comment]
Añado captura de pantalla.
2015-10-21-095021_1366x768_scrot

**Comment by kikocorreoso** [comment]
@yamila-moreno te encargas de mergear y desplegar?

gracias.

**Comment by yamila-moreno** [comment]
claro!

On 21 October 2015 at 10:20, kikocorreoso <notifications@github.com> wrote:

> @yamila-moreno <https://github.com/yamila-moreno> te encargas de mergear
> y desplegar?
>
> gracias.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-spain/association-web/pull/4#issuecomment-149812853>
> .
>



-- 
Yamila  Moreno Suárez
http://dendarii.es
http://moduslaborandi.net

**Comment by yamila-moreno** [comment]
done!
revisad porfi

On 21 October 2015 at 11:31, Yamila Moreno Suárez <yamila.ms@gmail.com>
wrote:

> claro!
>
> On 21 October 2015 at 10:20, kikocorreoso <notifications@github.com>
> wrote:
>
>> @yamila-moreno <https://github.com/yamila-moreno> te encargas de mergear
>> y desplegar?
>>
>> gracias.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/python-spain/association-web/pull/4#issuecomment-149812853>
>> .
>>
>
>
>
> --
> Yamila  Moreno Suárez
> http://dendarii.es
> http://moduslaborandi.net
>



-- 
Yamila  Moreno Suárez
http://dendarii.es
http://moduslaborandi.net

**Comment by kikocorreoso** [comment]
Perfect, thanks!!!!

2015-10-21 11:34 GMT+02:00 Yamila <notifications@github.com>:

**Pull request merged**
